directories:
  output: release
  buildResources: build
appId: com.electron.app
productName: Craft Automation CPQ
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
      - src/data/**/*
      - '!node_modules/sqlite3/build-tmp-napi-*/**/*'
asarUnpack:
  - node_modules/sqlite3/**/*
win:
  target:
    - target: dir
      arch:
        - x64
  sign: false
  certificateFile: null
  certificatePassword: <stripped sensitive data>
  verifyUpdateCodeSignature: false
  signDlls: false
  rfc3161TimeStampServer: null
  timeStampServer: null
nsis:
  oneClick: false
  perMachine: true
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Craft Automation CPQ
  license: LICENSE
  deleteAppDataOnUninstall: false
extraMetadata:
  main: dist-electron/main.cjs
npmRebuild: false
buildDependenciesFromSource: false
nodeGypRebuild: false
afterPack: scripts/after-pack.cjs
electronVersion: 28.3.3
